#!/bin/bash

# Go to project inside the code directory
function c {
  cd ~/code/$1
}

# Open sublime text with full_screen by default
function e {

  # If there's no arguments use current folder
  if [[ -z $1 ]]; then
    args='.'
  else
    args=$1
  fi

  subl -n --command toggle_full_screen $args
}

# Change the iterm2 profile programatically
function iterm_profile {
  if [[ -z $1 ]]; then
    profile="Default"
  else
    profile=$1
  fi

  echo -ne "\033]50;SetProfile=$profile\a"
}
